### ISSUE TITLE
feature:If along with Just login button you could also add Signup button in navbar 

### ISSUE THREAD

**Issue by jeevikasirwani** [ajaynegi45/Uttarakhand-Culture-Preservation-Project#86]

**Comment by ajaynegi33** [comment]
Hi @jeevikasirwani,

Thank you for your suggestion! However, displaying both the login and signup buttons in the navbar might clutter the interface. Instead, users can simply click on the login button, and from there, they will have the option to either log in or sign up. This streamlined approach maintains a cleaner design while still providing users with the necessary functionality.

Let me know if you have any further questions or concerns.
